### ISSUE TITLE
Always crashes

### ISSUE THREAD

**Issue by hydrargyrum** [samwho/spacer#3]
- start spacer (with `RUST_BACKTRACE=full`)
- send one line on stdin
- wait one second

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: The system's UTC offset could not be determined', src/main.rs:121:48
stack backtrace:
   0:     0x55a90c438073 - std::backtrace_rs::backtrace::libunwind::trace::he0156af2558114c2
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a90c438073 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e2672bcf5105eb5
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a90c438073 - std::sys_common::backtrace::_print_fmt::haa919a14d8d859ec
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55a90c438073 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf15e8f9e6884dd5f
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55a90c4525dc - core::fmt::write::he42254d9e3c27115
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/fmt/mod.rs:1202:17
   5:     0x55a90c423635 - std::io::Write::write_fmt::hfb37e0ab3a125c66
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/io/mod.rs:1679:15
   6:     0x55a90c4259f4 - std::sys_common::backtrace::_print::h8078bdb0e2e92b53
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55a90c4259f4 - std::sys_common::backtrace::print::h09fd65486fb9c4f7
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55a90c4259f4 - std::panicking::default_hook::{{closure}}::hb89b98c578903f40
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:295:22
   9:     0x55a90c425634 - std::panicking::default_hook::h27aa44be03b01ac8
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:314:9
  10:     0x55a90c425fd3 - std::panicking::rust_panic_with_hook::he7013d2ea706cde0
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:698:17
  11:     0x55a90c438677 - std::panicking::begin_panic_handler::{{closure}}::hd66fe345adc7bed2
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:588:13
  12:     0x55a90c4381b4 - std::sys_common::backtrace::__rust_end_short_backtrace::ha2b47ffe9f27aed9
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55a90c425cc2 - rust_begin_unwind
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:584:5
  14:     0x55a90c3b80e3 - core::panicking::panic_fmt::hbfca70bd08ba6212
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/panicking.rs:142:14
  15:     0x55a90c3b81c3 - core::result::unwrap_failed::h24a3d44a1b5e0507
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/result.rs:1785:5
  16:     0x55a90c3bbdb7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c656f72c535e8b9
  17:     0x55a90c3c66a8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha9d1edba3a56d9bd
  18:     0x55a90c4171b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd9de39939d514e1f
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/alloc/src/boxed.rs:1940:9
  19:     0x55a90c4171b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9dcf0031058cd523
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/alloc/src/boxed.rs:1940:9
  20:     0x55a90c4171b3 - std::sys::unix::thread::Thread::new::thread_start::h4c7fb5fbc81b5e1c
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys/unix/thread.rs:108:17
  21:     0x7f291c44fb43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  22:     0x7f291c4e1a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  23:                0x0 - <unknown>
```

**Comment by samwho** [comment]
This should be fixed in v0.1.1. Sorry about that!

If you could update and report back, that would be much appreciated.
